services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - php
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    container_name: php
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: ./docker/php
      dockerfile: dockerfile
    volumes:
      - ./backend:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/90-xdebug.ini:/usr/local/etc/php/conf.d/90-xdebug.ini

  symfony:
    container_name: symfony
    build:
      context: ./docker/symfony
      dockerfile: dockerfile
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html

  database:
    image: mysql:8
    container_name: products-db
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
    environment:
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "user"
      MYSQL_DATABASE: "products"
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./database:/var/lib/mysql