FROM php:8.1-cli-alpine

RUN apk add --no-cache bash curl git
RUN php -r "copy('https://getcomposer.org/installer', '/usr/bin/composer-setup.php');"
WORKDIR /usr/bin
RUN php composer-setup.php
RUN mv ./composer.phar /usr/bin/composer

RUN curl -o symfony.sh 'https://dl.cloudsmith.io/public/symfony/stable/setup.alpine.sh'
RUN chmod +x ./symfony.sh
RUN ./symfony.sh
RUN apk add symfony-cli

